# Site settings
title: Decoding Life
header-img: img/home-bg.png
email: justinddaniel@gmail.com
copyright_name: justinddaniel
description: > # this means to ignore newlines until "baseurl:"
  Better living through science, reason, and programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  justinddaniel
learn_profile: justinddaniel
email_username: justinddaniel@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
